ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER SKYSCRAPER IDENTIFIED BY SKYSCRAPER_PWD;

GRANT CREATE SESSION TO SKYSCRAPER;
GRANT CREATE TABLE TO SKYSCRAPER;

ALTER USER SKYSCRAPER quota unlimited on USERS;

create sequence request_number_seq start with 100 increment by 1;